export const IPC_CHANNELS = {
  DB_QUERY: "db:query",
  DB_MUTATE: "db:mutate",
  DB_MIGRATE: "db:migrate",
  DB_EXPORT: "db:export",
  DB_IMPORT: "db:import",
  MEDIA_SAVE: "media:save",
  MEDIA_DELETE: "media:delete",
  MEDIA_GET_THUMBNAIL: "media:getThumbnail",
  MEDIA_OPEN_EXTERNAL: "media:openExternal",
  FS_GET_PATH: "fs:getPath",
  FS_SHOW_OPEN_DIALOG: "fs:showOpenDialog",
  FS_SHOW_SAVE_DIALOG: "fs:showSaveDialog",
  APP_GET_VERSION: "app:getVersion",
  APP_QUIT: "app:quit",
  WINDOW_MINIMIZE: "window:minimize",
  WINDOW_MAXIMIZE: "window:maximize",
  WINDOW_CLOSE: "window:close",
} as const;
